/**
 * The billing service's read model.
 *
 * Field names are copied verbatim from uploads/billing_service_db.sql (Laravel /
 * MySQL 8): tenants → stores → licenses → invoices, packages + pricing_tiers,
 * license_events (webhook idempotency) and sync_queue (retry to
 * /internal/license-sync).
 *
 * That service owns this data and has its own database. This app does not model
 * those tables in Prisma — it reads them through src/lib/billing/client.ts.
 */

/** licenses.status — pending|trialing|active|past_due|blocked|canceled|expired. */
export type LicenseStatus = 'pending' | 'trialing' | 'active' | 'past_due' | 'blocked' | 'canceled' | 'expired';

/** invoices.status — draft|open|paid|void|uncollectible. */
export type InvoiceStatus = 'draft' | 'open' | 'paid' | 'void' | 'uncollectible';

export interface Tenant {
  id: string;
  slug: string;
  name: string;
  stripe_customer_id: string | null;
  internal_api_url: string;
  admin_email: string;
  /** Present only for superadmin; the plain key is never stored. */
  api_key_hint: string | null;
  stores: number;
  licenses: number;
  onboarded_at: string | null;
  /** Soft delete — NULL = active. */
  archived_at: string | null;
}

export interface Package {
  id: string;
  code: string;
  name: string;
  description: string | null;
  stripe_price_id: string | null;
  /** 1 = core, always active, no Stripe billing. */
  is_free: boolean;
  is_active: boolean;
  licenses: number;
}

export interface PricingTier {
  id: string;
  package: string;
  min_qty: number;
  /** NULL = no upper limit. */
  max_qty: number | null;
  unit_price: number;
  currency: string;
  valid_from: string;
  /** NULL = currently in effect. */
  valid_to: string | null;
}

export interface License {
  id: string;
  tenant: string;
  /** NULL = a tenant-scope licence (store_id NULL). */
  store: string | null;
  package: string;
  /** NULL for core, or before the Stripe subscription is created. */
  stripe_subscription_id: string | null;
  /** Negotiated discount, 0.00–100.00. */
  discount_percent: number | null;
  status: LicenseStatus;
  trial_ends_at: string | null;
  current_period_end: string | null;
  cancel_at_period_end: boolean;
  unit_price: number;
}

export interface Invoice {
  id: string;
  tenant: string;
  store: string | null;
  /** Deduplication key. */
  stripe_invoice_id: string;
  amount_due: number;
  amount_paid: number;
  currency: string;
  status: InvoiceStatus;
  period: string;
  /** invoice_pdf_url is generated by Stripe asynchronously. */
  pdf: boolean;
}

export interface LicenseEvent {
  id: string;
  license: string;
  event_type: string;
  /** UNIQUE in the source table — webhook idempotency. NULL = internal event. */
  stripe_event_id: string | null;
  occurred_at: string;
}

export interface SyncQueueRow {
  id: number;
  license: string;
  attempts: number;
  next_retry: string;
  last_error: string | null;
}

export interface BillingSnapshot {
  tenants: Tenant[];
  packages: Package[];
  tiers: PricingTier[];
  licenses: License[];
  invoices: Invoice[];
  events: LicenseEvent[];
  sync: SyncQueueRow[];
  /** True when the rows come from the fixture set rather than the live service. */
  fixture: boolean;
}

/**
 * Status → Badge tone, taken from the column comments in the SQL dump. The label
 * is always the raw English DB value: status is data, not copy.
 */
export const LICENSE_STATUS_TONE: Record<LicenseStatus, 'neutral' | 'info' | 'success' | 'danger'> = {
  pending: 'neutral',
  trialing: 'info',
  active: 'success',
  past_due: 'danger',
  blocked: 'danger',
  canceled: 'neutral',
  expired: 'neutral',
};

export const INVOICE_STATUS_TONE: Record<InvoiceStatus, 'neutral' | 'warning' | 'success' | 'danger'> = {
  draft: 'neutral',
  open: 'warning',
  paid: 'success',
  void: 'neutral',
  uncollectible: 'danger',
};

export const LICENSE_STATUSES = Object.keys(LICENSE_STATUS_TONE) as LicenseStatus[];
export const INVOICE_STATUSES = Object.keys(INVOICE_STATUS_TONE) as InvoiceStatus[];

/** Euro amounts everywhere in the console, French formatting, 2 decimals. */
export function euro(value: number | null | undefined): string {
  if (value == null) return '—';
  return value.toLocaleString('fr-FR', { style: 'currency', currency: 'EUR', minimumFractionDigits: 2 });
}
